### ISSUE TITLE
Confusing token expiration default values and options

### ISSUE THREAD

**Issue by yumaoka** [ibm-cloud-docs/appid#358]
https://cloud.ibm.com/docs/services/appid?topic=appid-customizing-tokens#customizing-tokens

The table below in the page above has a couple of issues.

1. Value type in the actual configuration is actually seconds. e.g. default access token expiration value is 3600 (seconds = 60 minutes).
2. Options for Refresh/Anonymous is "Any value between 1 and 9" in this table, but the default value is 30.

---
You can customize your tokens [in the GUI](/docs/services/appid?topic=appid-customizing-tokens#configuring-tokens-ui) or by using [the API](/docs/services/appid?topic=appid-customizing-tokens#configuring-tokens-api){: external} by setting the lifespan validity or by adding custom claims to your tokens. Check out the following table to see how lifespan is configured or continue reading to learn about mapping custom attributes.

<table>
  <caption>Table 1. Token customization options</caption>
  <tr>
    <th>Token type</th>
    <th>Value type</th>
    <th>Default</th>
    <th>Options</th>
  </tr>
  <tr>
    <td>Access</td>
    <td>Minutes</td>
    <td>60</td>
    <td>Any value between 5 and 1440</td>
  </tr>
  <tr>
    <td>Identity</td>
    <td>Minutes</td>
    <td>60</td>
    <td>Any value between 5 and 1440</td>
  </tr>
  <tr>
    <td>Refresh</td>
    <td>Days</td>
    <td>30</td>
    <td>Any value between 1 and 9</td>
  </tr>
  <tr>
    <td>Anonymous</td>
    <td>Days</td>
    <td>30</td>
    <td>Any value between 1 and 9</td>
  </tr>
</table>

**Comment by smguilia** [comment]
Hi @yumaoka,

Thank you for pointing this out. I incorporated your feedback into the documentation and the changes will go out with the next push to production. Please continue to leave feedback in the future. We're always looking for ways to make the documentation better.

-Shawna
