### ISSUE TITLE
Getting 'invalid token' error with app id integrated with Angular application

### ISSUE THREAD

**Issue by VinodGoddli** [ibm-cloud-docs/appid#364]
Currently i'm getting 'invalid token' error after entering credentials in App Id login screen. This app id service is integrated with angular appliation. I have this application in location and it'working fine but same application deployed to cloud and while testing i'm getting 'invalid token' error.

**Comment by smguilia** [comment]
Hi @VinodGoddli,

Thanks for taking the time to open feedback! I see that you're already speaking with the development team on Slack. If any updates to the docs are needed based on that conversation, I'll work with the dev team to pull them in. 

If you have further feedback or suggestions to make the docs better, please don't hesitate to open another issue in the future.

- Shawna
