### ISSUE TITLE
Step-3 of installing the adapter no longer works with openshift

### ISSUE THREAD

**Issue by git2g** [ibm-cloud-docs/appid#365]
Please fix [Step-3](https://cloud.ibm.com/docs/appid?topic=appid-istio-adapter#istio-install-adapter) as that [mixer policy is deprecated](https://istio.io/docs/tasks/policy-enforcement/enabling-policy/) and doesn't work on ocp-4.3. I'm stuck on `Waiting for resources to become ready...` after trying 
`istioctl manifest apply --set values.global.disablePolicyChecks=false --set values.pilot.policy.enabled=true`

**Comment by smguilia** [comment]
Hi @git2g,

Thank you for opening feedback on the App ID documentation. We're looking into it with the development team and we'll post an update with any changes to the documentation. 

If you're interested, you can always reach out directly to the development team on Slack: https://cloud.ibm.com/docs/appid?topic=appid-faq#faq-slack

Thank you,
Shawna

**Comment by smguilia** [comment]
Hi @git2g 

Thanks again for opening feedback.

I made a few minor updates to the docs, but the command that you pointed out does work as expected when we tested internally. If you have further questions, please open a support ticket or reach out to the development team directly on slack. 

Thank you,
Shawna
