### ISSUE TITLE
Custom SignUp using AppId

### ISSUE THREAD

**Issue by coolgary90** [ibm-cloud-docs/appid#366]
I am create Custom UI Login screen and communicate with AuthorizationDelegate using AppId services but i didn't able to find out how can I use my own custom  SignUp UI with AppId.  Please let me know how we can integrate custom sign up UI with AuthorizationDelegate.

**Comment by smguilia** [comment]
Hi @coolgary90,

Sorry for the delay in my response. Thanks for taking the time to open an issue. I've opened an issue internally to investigate your feedback and update the docs. For help while I'm working on this, please join our slack channel. 

https://cloud.ibm.com/docs/appid?topic=appid-faq#faq-slack
