### ISSUE TITLE
video in doc is set to private

### ISSUE THREAD

**Issue by DseeHappy** [ibm-cloud-docs/appid#368]
Please set video in doc as public to see what it is about.

**Comment by DseeHappy** [comment]
https://cloud.ibm.com/docs/appid?topic=appid-managing-idp

**Comment by smguilia** [comment]
Hi @DseeHappy,

Sorry for the delayed response. Thank you for opening this issue to let us know. I've started investigating to see how to get the video settings reverted back to public. I'll let you know when the change is merged. Please don't hesitate to leave feedback in the future if you see things that can be updated.

- Shawna

**Comment by smguilia** [comment]
Hi @DseeHappy, I was unable to locate the owner of the video to have the settings changed. I apologize for the inconvenience. I've removed the video from the docs. 

Thank you again. Please don't hesitate to leave more feedback in the future to help make the docs better!

-Shawna
