### ISSUE TITLE
Regex dialect is unclear

### ISSUE THREAD

**Issue by pgarrett-ibm** [ibm-cloud-docs/appid#370]
I'd appreciate if you could make it clear what regex dialect (Java? PCRE? ...) is in effect, in either the [Defining password policies](https://cloud.ibm.com/docs/appid?topic=appid-cd-strength) documentation or the [API documentation](https://us-south.appid.cloud.ibm.com/swagger-ui/#/Management%20API%20-%20Config/mgmt.set_cloud_directory_password_regex).  Apologies if its there and I missed it.

**Comment by smguilia** [comment]
Hi @pgarrett-ibm,

Sorry for the delayed response - Java is the dialect. I'll work to update the content with that clarification. Please don't hesitate to reach out again in the future if you have more questions.

-Shawna
