### ISSUE TITLE
Swagger has incorrect links to IAM

### ISSUE THREAD

**Issue by Marek-IBM** [ibm-cloud-docs/appid#373]
The IAM links to IBM Cloud don't work and return a 404 
![image](https://user-images.githubusercontent.com/81649711/116105035-f0255280-a67e-11eb-9203-d65511017ce4.png)
![image](https://user-images.githubusercontent.com/81649711/116105094-fc111480-a67e-11eb-9e2e-5389799d4276.png)

**Comment by smguilia** [comment]
Hi @Marek-IBM Thank you for opening an issue. The link has been updated and will be pushed to production as part of the next production deployment.
