### ISSUE TITLE
AppId and Kubernetes Ingress page needs clarification

### ISSUE THREAD

**Issue by smatzek** [ibm-cloud-docs/appid#374]
The page, https://cloud.ibm.com/docs/appid?topic=appid-kube-auth, [tutorial-kubernetes-auth.md](https://github.com/ibm-cloud-docs/appid/blob/master/tutorial-kubernetes-auth.md), some text that gave us a lot of confusion and made it take a long time to correctly set up AppID with Kubernetes Ingress.

The step:
"Optional: If your app supports the web app strategy in addition to, or instead of, the API strategy, add the `nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2-<App_ID_service_instance_name>/start?rd=$escaped_request_uri annotation.`
"
is confusing because of the terms "web app strategy" and "API strategy". It confused us because we were somewhat familiar with the WebAppStrategy and APIStrategy auth methods with passport as noted on the "Backend Apps" and "Web Apps" pages in the AppID doc:
```
var APIStrategy = require('ibmcloud-appid').APIStrategy; 
const WebAppStrategy = require("ibmcloud-appid").WebAppStrategy;
```

Since we were enabling a web application with auth through Ingress and did not want to change this app's code to use WebAppStrategy we did not do this optional step, but this step ends up being REQUIRED if you have a web app that you want to secure with AppID and K8s ingress.

I would suggest removing the terms "web app strategy" and "API strategy" from the two sections in the Ingress doc and replacing them with more general terms such as:
"If your app is a web app, in addition to or instead of providing APIs, add ..."

and similar change lower in the doc in the "Verify that App ID authentication is enforced for your apps" section.

**Comment by smatzek** [comment]
@Jordy24 FYI

**Comment by Jordy24** [comment]
I would also suggest that 

The step:
"Optional: If your app supports the web app strategy in addition to, or instead of, the API strategy, add the nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2-<App_ID_service_instance_name>/start?rd=$escaped_request_uri annotation.
"
should be placed before step number 2, basically making it easy for a person who wants to just protect their iks cluster and not have to change their code..

**Comment by smguilia** [comment]
Hi @smatzek and @Jordy24 

Thank you for opening this! Sorry for the delayed response. I've updated the doc with your suggestions. Please don't hesitate to reach out again if you have more feedback.

Shawna
