### ISSUE TITLE
Java Sample App Does not compile

### ISSUE THREAD

**Issue by ronther1** [ibm-cloud-docs/appid#375]
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[INFO] 2 errors

**Comment by smguilia** [comment]
Hi @ronther1,

Thank you for opening this. I've forwarded this information to our development team.
