### ISSUE TITLE
Example Java Web Sample program does not compile

### ISSUE THREAD

**Issue by ronther1** [ibm-cloud-docs/appid#376]
The Sample Java Web application does not run.  I get:
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.

I added the following to the pom.xml:
  <properties>
       <maven.compiler.source>1.8</maven.compiler.source>
       <maven.compiler.target>1.8</maven.compiler.target>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

And got this error:
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.2.1:start (default-cli) on project libertySample: CWWKM2002E: Failed to invoke [/Users/ronther1/Development/app-id-sample-java-master/WebApplication/target/liberty/wlp/bin/server, start, sample]. RC= 22 but expected=[0, 1]. -> [Help 1]

**Comment by smguilia** [comment]
Hi @ronther1,

Thank you for opening this. I've forwarded this feedback to our development team.
