### ISSUE TITLE
Delete user profile with REST instruction incorrect

### ISSUE THREAD

**Issue by cpschult** [ibm-cloud-docs/appid#378]
In section 'Deleting a profile with the API' step 3 says:
> 3. By using the ID that you obtained in the previous step, make a DELETE request to the /users endpoint to see their full user profile.

Should that be like this instead?
>3. By using the ID that you obtained in the previous step, make a DELETE request to the /users endpoint to *delete the profile*.

**Comment by smguilia** [comment]
Hi @cpschult,

Thank you for opening an issue! I've updated the documentation. Please don't hesitate to open more issues in the future if you come across similar issues or have idea's for improvements to the the documentation.

-- shawna
