### ISSUE TITLE
Policy: Avoid Password Reuse -> max 8 times, not 10 as the documentation says

### ISSUE THREAD

**Issue by xwxnumber1xwx** [ibm-cloud-docs/appid#379]

**Comment by xwxnumber1xwx** [comment]
https://cloud.ibm.com/docs/appid?topic=appid-cd-strength

**Comment by smguilia** [comment]
Hi @xwxnumber1xwx,

Thank you for reporting. We've updated the documentation. Please don't hesitate to reach out in the future if you encounter other issues or if you have ideas for doc improvements.

 -- Shawna
