### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by mabinraja** [ibm-cloud-docs/appid#381]
Software desk

**Comment by hoko0116** [comment]
i don't know what the problem with this

**Comment by hoko0116** [comment]
i to see you soon and i'll soon love you guys

**Comment by hoko0116** [comment]
可以不要都英文嗎

**Comment by smguilia** [comment]
Please open an issue with specific details if there are defects in the docs or suggestions for the App ID service that we can help you with.
