### ISSUE TITLE
Keyword not replaced

### ISSUE THREAD

**Issue by haf-tech** [ibm-cloud-docs/appid#382]
The keyword
`{{{site.data.keyword.appid_short_notm}}`
is not replaced in the generated doc.

See section:
https://cloud.ibm.com/docs/appid?topic=appid-custom-auth#custom-auth-tech

**Comment by smguilia** [comment]
Thank you for pointing this out @haf-tech! I made the change internally as we're not actually able to merge PR contributions to this repository. 

Please don't hesitate to open another issue in the future if you come across other areas that the documentation can be improved.

- shawna
