### ISSUE TITLE
Documentation correction needed for S2S authorization for App ID 

### ISSUE THREAD

**Issue by TiffanyLiIBM** [ibm-cloud-docs/appid#384]
**Describe the bug**
The source is incorrectly documented as HPCS whereas it should have been App ID service in Service-to-Service Authorization section

**To Reproduce**
1. Go to the link and see point 4, element b
https://cloud.ibm.com/docs/appid?topic=appid-mng-data#enable-customer-keys-hpcs
2. See error

**Expected behavior**
Expected to see App ID as the source instead of HPCS

**Screenshots**
<img width="1613" alt="Screen Shot 2021-12-21 at 10 00 24 PM" src="https://media.github.ibm.com/user/56875/files/e275aa80-62a9-11ec-8c13-4e26dfd44441">

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by TiffanyLiIBM** [comment]
Please contact @nproddu for more details.

**Comment by smguilia** [comment]
Hi @TiffanyLiIBM! So sorry for the delayed response. I've made the update and pushed the change to production. Please  don't hesitate to open additional issues in the future if you come across any other defects or have ideas for improvement. We're always happy to receive feedback. 

Shawna
