### ISSUE TITLE
Broken link on ibm.com page

### ISSUE THREAD

**Issue by mekaufman** [ibm-cloud-docs/appid#389]
FYI @jigneshkvp I've moved this issue to the App ID area.

Original issue opened here https://github.com/ibm-cloud-docs/overview/issues/10

Hello,

The link to [Mobile App with serverless backend](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-serverless-mobile-backend) on the [AppId home page](https://www.ibm.com/cloud/app-id) does not work.

**Comment by h-romeus** [comment]
@jigneshkvp @mekaufman Thank you for opening this issue! This is a larger item that we will need to prioritize within our team. I've opened an issue internally that we will use for tracking and will be closing this issue for the time being. I will post here when there is an update available. Please don't hesitate to open additional feedback in the future as we're always looking for ways to improve our documentation.

- Hadassa
