### ISSUE TITLE
AppID is not supported on Openshift cluster

### ISSUE THREAD

**Issue by sanfordhuynh** [ibm-cloud-docs/appid#391]
Hi,

In this AppID doc, it states: "With IBM Cloud® App ID, you can consistently enforce policy-driven security by using the Ingress networking capability in IBM Cloud Kubernetes Service or Red Hat OpenShift on IBM Cloud" 

As one of the steps needed is to enable alb-oauth-proxy, however this is not supported on Openshift clusters only Kubernetes. Can the doc be edited to reflect this? 

 "With IBM Cloud® App ID, you can consistently enforce policy-driven security by using the Ingress networking capability in IBM Cloud Kubernetes Service" 

https://cloud.ibm.com/docs/appid?topic=appid-kube-auth

Proof ALB-Oauth is not supported: https://cloud.ibm.com/docs/openshift?topic=openshift-supported-cluster-addon-versions

**Comment by h-romeus** [comment]
Hi @sanfordhuynh, thank you for opening this issue! I've addressed your feedback and reviewed with the development team. The update will be available soon. Please don't hesitate to open additional feedback in the future.
- Hadassa
