### ISSUE TITLE
App ID Docs Issue

### ISSUE THREAD

**Issue by teoks** [ibm-cloud-docs/appid#394]
Hi Team, 

Can we get the public App ID documentation updated?
<img width="602" alt="image" src="https://github.com/ibm-cloud-docs/appid/assets/12643515/f60e2c94-9d9e-45c8-8c1b-0246f52cbbf9">

The Identity Provider - IBMid - documentation link is link to test.cloud.ibm.com. 
I have a support case open for this documentation issue too. CS3449179

**Comment by smguilia** [comment]
I have spoken with the App ID development team and the IBMid integration is intentionally internal only which is why the URL leads to a staging doc.
