### ISSUE TITLE
URL uses localhost instead of using the public Endpoint

### ISSUE THREAD

**Issue by dventurait** [ibm-cloud-docs/appid#395]
In this Doc https://cloud.ibm.com/docs/appid?topic=appid-app&interface=ui

The curl command in the bottom of the doc is:
```
curl -X POST http://localhost:6002/oauth/v4/39a37f57-a227-4bfe-a044-93b6e6060b61/token    -H 'Authorization: Basic base64Encoded{clientId:secret}'    -H 'Content-Type: application/x-www-form-urlencoded'    -d grant_type=client_credentials
```

This is wrong since is using localhost and a specific tenant id.

Please update it using this curl command:

```
curl -X POST https://<region>.appid.cloud.ibm.com/oauth/v4/<tenantID>/token -H 'Authorization: Basic base64Encoded{clientId:secret}' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials'
```

**Comment by atskae** [comment]
Hello! I am trying the updated command, using `clientId`, `secret`, and `tenantId` from my AppID instance,  but I get:
```
{"statusCode":401,"error_description":"Invalid Credentials","error":"invalid_client"}
```

Is the command in the docs still up to date?

(edit) Nevermind, I figured out the issue. I did not base64-encode the client credentials properly 😅 (I was encoding a newline character by mistake).
