### ISSUE TITLE
Download Sample - no link

### ISSUE THREAD

**Issue by otrebor** [ibm-cloud-docs/appid#396]
The page https://cloud.ibm.com/docs/appid?topic=appid-getting-started
suggests to download a sample. I can't find a link to it tho.

Thank you very much

Roberto

**Comment by hlucey** [comment]
Hello @otrebor, 

I'm sorry you had trouble downloading the sample. To get to the link you must complete [Step 1: Create a service instance](https://cloud.ibm.com/docs/appid?topic=appid-getting-started#create). 

After you complete this, you are redirected to the App ID overview page. From the overview page, you can click the button to download the sample. 

<img width="1430" alt="Screenshot 2024-02-20 at 8 01 32 PM" src="https://github.com/ibm-cloud-docs/appid/assets/42588404/e215fb8e-d5d3-4da2-9fbc-1c28442c7f9a">

Don't hesitate to reach out if this doesn't solve your problem.

Haley
