### ISSUE TITLE
App ID >  Explore related content > Custom sign-in experience > urls not working

### ISSUE THREAD

**Issue by gandradeglez** [ibm-cloud-docs/appid#398]
https://cloud.ibm.com/docs/appid?topic=appid-rellinks#rellinks-custom

URLs in Custom sign-in experience are not working, both urls redirects you to https://www.ibm.com/blog/

**Comment by smguilia** [comment]
Hello, thank you for opening this issue. Unfortunately both of these blogs are old and there is not a current place to link. Closing this issue.
