### ISSUE TITLE
Typo in leading content

### ISSUE THREAD

**Issue by markjmeredith** [ibm-cloud-docs/appid#399]
This topic is about App ID but mentions Security and Compliance Center in the first paragraph.

**Comment by smguilia** [comment]
@markjmeredith can you tell me which page you found this on?

**Comment by markjmeredith** [comment]
@smguilia sorry, i thought it would have grabbed the page with the issue. https://cloud.ibm.com/docs/appid?topic=appid-known-issues-limits

**Comment by smguilia** [comment]
No worries! I always think it's going to do that too. I made the update. Thanks for pointing it out!
