### ISSUE TITLE
Does AppID offer integration with IBMid identity provider?

### ISSUE THREAD

**Issue by ewan-chalmers** [ibm-cloud-docs/appid#400]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/appid?topic=appid-managing-idp 

### What do you think needs to be updated?

Does AppID offer integration with IBMid identity provider? If it does, then how? Why is it not documented?

### Anything else?

The only reference I found to IBMid in the AppID docs on IBM Cloud was in the section https://cloud.ibm.com/docs/appid?topic=appid-preregister. There and only there, `ibmid` appears as a valid option for `idp`.

**Comment by smguilia** [comment]
Thank you for opening this feedback! Addressed the extra reference to ibmid and we talked internally.
